{% set version = "2.0.16" %}

package:
  name: bob.learn.boosting
  version: {{ version }}

source:
  fn: bob.learn.boosting-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.learn.boosting/bob.learn.boosting-{{ version }}.zip
  md5: e3b395cded0587a609c022e1b213865b

build:
  entry_points:
    - boosting_example.py = bob.learn.boosting.examples.mnist:main
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - numpy
    - scipy
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.62.*
    - cmake
    - pkg-config

  run:
    - python
    - numpy
    - scipy
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.62.*

test:
  commands:
    - boosting_example.py --help
    - nosetests -sv bob.learn.boosting

  imports:
    - bob
    - bob.learn
    - bob.learn.boosting
    - bob.learn.boosting.examples
    - bob.learn.boosting.tests

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Boosting framework for Bob

extra:
  recipe-maintainers:
    - 183amir
